name: Update on odoo13-test

on:
    push:
        branches:
            - 13.0

jobs:
    deploy-test-13:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install SSH Key
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  known_hosts: "placeholder" # We get the Known Hosts in the next step, but this key is required.

            - name: Adding Known Hosts
              run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

            - name: Deploy with rsync
              run: rsync -azvh $GITHUB_WORKSPACE/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/opt/odoo13/custom-addons/calyx/third-party-paid --delete

            - name: Restart Odoo
              uses: garygrossgarten/github-action-ssh@release
              with:
                  command: service odoo13 restart
                  host: "${{ secrets.SSH_HOST }}"
                  username: ${{ secrets.SSH_USER }}
                  privateKey: ${{ secrets.SSH_PRIVATE_KEY}}
